# Generated by Django 4.2.7 on 2025-11-22 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='Telegram foydalanuvchi ID', null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sotuvchi',
                'verbose_name_plural': 'Sotuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('contacted', "Bog'langan"), ('qualified', 'Sifatli'), ('converted', 'Aylantirilgan'), ('lost', "Yo'qotilgan")], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(default='google_sheets', help_text='Lid manbasi', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('sheets_row_id', models.IntegerField(blank=True, help_text='Google Sheets dagi qator ID', null=True, unique=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.seller')),
            ],
            options={
                'verbose_name': 'Lid',
                'verbose_name_plural': 'Lidlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', 'status'], name='leads_lead_seller__acb6f4_idx'), models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'), models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx')],
            },
        ),
    ]
