# Generated by Django 4.2.7 on 2025-11-27 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('leads', '0002_lead_follow_up_plan_lead_followup_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('attended', 'Attended'), ('no_show', 'No-show'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('sales_offer', 'Sales Offer Made'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('actual_attendance_time', models.DateTimeField(blank=True, null=True)),
                ('trial_completed_at', models.DateTimeField(blank=True, null=True)),
                ('sales_offer_made_at', models.DateTimeField(blank=True, null=True)),
                ('salesperson_notes', models.TextField(blank=True)),
                ('pre_trial_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('post_trial_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.group')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='leads.lead')),
            ],
            options={
                'ordering': ['-scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='TrialReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_trial_reminder_scheduled_at', models.DateTimeField()),
                ('pre_trial_reminder_sent', models.BooleanField(default=False)),
                ('post_trial_reminder_scheduled_at', models.DateTimeField()),
                ('post_trial_reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='trials.trial')),
            ],
            options={
                'ordering': ['pre_trial_reminder_scheduled_at'],
                'indexes': [models.Index(fields=['pre_trial_reminder_sent'], name='trials_tria_pre_tri_092fde_idx'), models.Index(fields=['post_trial_reminder_sent'], name='trials_tria_post_tr_7b1f8b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['lead'], name='trials_tria_lead_id_c20a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['scheduled_date'], name='trials_tria_schedul_4572e9_idx'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['status'], name='trials_tria_status_e769d3_idx'),
        ),
    ]
