# Generated by Django 4.2.7 on 2025-11-27 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('source', models.CharField(choices=[('google_sheets', 'Google Sheets'), ('excel_upload', 'Excel Upload'), ('csv_upload', 'CSV Upload'), ('manual', 'Manual Entry'), ('other', 'Other')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('google_sheets', 'Google Sheets'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('google_sheet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('contacted', 'Contacted'), ('snoozed', 'Snoozed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_deadline', models.DateTimeField()),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.IntegerField(default=0)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='leads.lead')),
            ],
            options={
                'ordering': ['contact_deadline'],
                'indexes': [models.Index(fields=['status'], name='leads_leadr_status_270003_idx'), models.Index(fields=['contact_deadline'], name='leads_leadr_contact_13864e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='leads_lead_phone_709d42_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='leads_lead_assigne_3f8857_idx'),
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['status'], name='leads_impor_status_71be08_idx'),
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['import_type'], name='leads_impor_import__e3f006_idx'),
        ),
    ]
