# Generated by Django 4.2.7 on 2025-11-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='follow_up_plan',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='followup_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_followup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('instagram_ads', 'Instagram Ads'), ('telegram_bot', 'Telegram Bot'), ('whatsapp', 'WhatsApp'), ('landing_page', 'Landing Page'), ('google_sheets', 'Google Sheets'), ('excel_upload', 'Excel Upload'), ('csv_upload', 'CSV Upload'), ('call_tracking', 'Call Tracking'), ('manual', 'Manual Entry'), ('other', 'Other')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('trial_scheduled', 'Trial Scheduled'), ('trial_attended', 'Trial Attended'), ('trial_no_show', 'Trial No-show'), ('sales_offer', 'Sales Offer'), ('decision_pending', 'Decision Pending'), ('enrolled', 'Enrolled'), ('lost', 'Lost'), ('reactivation', 'Reactivation')], default='new', max_length=20),
        ),
    ]
