# Generated by Django 4.2.7 on 2025-12-01 08:07

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('sales_manager', 'Sales Manager'), ('sales', 'Sales')], default='sales', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active_sales', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_script', models.TextField(help_text='Sotuv scripti va bonus eslatmalar')),
                ('duration_minutes', models.IntegerField(help_text='Dars davomiyligi (daqiqa)')),
                ('lessons_per_week', models.IntegerField(help_text='Haftasiga darslar soni')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('days', models.CharField(choices=[('odd', 'Toq kunlar'), ('even', 'Juft kunlar'), ('daily', 'Har kuni')], max_length=10)),
                ('time', models.TimeField()),
                ('capacity', models.IntegerField()),
                ('current_students', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('youtube', 'Youtube'), ('organic', 'Organic'), ('form', 'Forma'), ('excel', 'Excel'), ('google_sheets', 'Google Sheets')], default='form', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('contacted', 'Aloqa qilindi'), ('interested', 'Qiziqmoqda'), ('trial_registered', 'Sinovga yozildi'), ('trial_attended', 'Sinovga keldi'), ('trial_not_attended', 'Sinovga kelmadi'), ('offer_sent', 'Sotuv taklifi'), ('enrolled', 'Kursga yozildi'), ('lost', "Yo'qotilgan lid"), ('reactivation', 'Qayta aloqa lid')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lost_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_sales', models.ForeignKey(blank=True, limit_choices_to={'role': 'sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('enrolled_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.group')),
                ('interested_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrialLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('result', models.CharField(blank=True, choices=[('attended', 'Keldi'), ('not_attended', 'Kelmadi'), ('offer_sent', 'Sotuv taklifi'), ('accepted', 'Qabul qildi'), ('rejected', 'Rad etdi')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='crm_app.group')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='crm_app.lead')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.room')),
            ],
        ),
        migrations.CreateModel(
            name='Reactivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_since_lost', models.IntegerField()),
                ('reactivation_type', models.CharField(choices=[('7_days', '7 kun'), ('14_days', '14 kun'), ('30_days', '30 kun')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(blank=True, choices=[('contacted', 'Aloqa qilindi'), ('interested', 'Qiziqmoqda'), ('no_response', "Javob yo'q")], max_length=20)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactivations', to='crm_app.lead')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.room'),
        ),
        migrations.AddField(
            model_name='group',
            name='trial_students',
            field=models.ManyToManyField(blank=True, related_name='trial_groups', to='crm_app.lead'),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='crm_app.lead')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_contacts', models.IntegerField(default=0)),
                ('daily_followups', models.IntegerField(default=0)),
                ('followup_completion_rate', models.FloatField(default=0.0)),
                ('trials_registered', models.IntegerField(default=0)),
                ('trials_to_sales', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('response_time_minutes', models.FloatField(default=0.0)),
                ('overdue_count', models.IntegerField(default=0)),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('sales', 'date')},
            },
        ),
    ]
