# Generated by Django 4.2.7 on 2025-12-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triallesson',
            name='sales_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
