# Generated by Django 4.2.7 on 2025-12-01 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_followup_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='absent_from',
            field=models.DateTimeField(blank=True, help_text='Ishda emaslik boshlanish vaqti', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='absent_reason',
            field=models.TextField(blank=True, help_text='Ishda emaslik sababi'),
        ),
        migrations.AddField(
            model_name='user',
            name='absent_until',
            field=models.DateTimeField(blank=True, help_text='Ishda emaslik tugash vaqti', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_absent',
            field=models.BooleanField(default=False, help_text='Manager tomonidan ishda emasligi belgilangan'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_on_leave',
            field=models.BooleanField(default=False, help_text='Ishdan ruxsat olgan'),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(help_text='Ruxsat sababi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Rad etish sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
