# Generated by Django 4.2.7 on 2025-12-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_user_absent_from_user_absent_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='end_time',
            field=models.TimeField(blank=True, help_text="Ruxsat tugash vaqti (bo'sh bo'lsa butun kun)", null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_time',
            field=models.TimeField(blank=True, help_text="Ruxsat boshlanish vaqti (bo'sh bo'lsa butun kun)", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_end_time',
            field=models.TimeField(blank=True, help_text='Ish tugash vaqti (masalan: 18:00)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_friday',
            field=models.BooleanField(default=True, help_text='Juma ish kuni'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_monday',
            field=models.BooleanField(default=True, help_text='Dushanba ish kuni'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_saturday',
            field=models.BooleanField(default=False, help_text='Shanba ish kuni'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_start_time',
            field=models.TimeField(blank=True, help_text='Ish boshlanish vaqti (masalan: 09:00)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_sunday',
            field=models.BooleanField(default=False, help_text='Yakshanba ish kuni'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_thursday',
            field=models.BooleanField(default=True, help_text='Payshanba ish kuni'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_tuesday',
            field=models.BooleanField(default=True, help_text='Seshanba ish kuni'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_wednesday',
            field=models.BooleanField(default=True, help_text='Chorshanba ish kuni'),
        ),
    ]
