# Generated by Django 4.2.7 on 2025-12-01 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_leaverequest_end_time_leaverequest_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Xabar mavzusi', max_length=200)),
                ('message', models.TextField(help_text='Xabar matni')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('normal', 'Oddiy'), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='normal', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('telegram_sent', models.BooleanField(default=False, help_text='Telegram orqali yuborilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.ManyToManyField(limit_choices_to={'role': 'sales'}, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(limit_choices_to={'role__in': ['admin', 'sales_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
