# Generated by Django 4.2.7 on 2025-12-01 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_salesmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='salesmessage',
            name='read_at',
        ),
        migrations.AddField(
            model_name='salesmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salesmessage',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Shoshilinch'), ('high', 'Yuqori'), ('normal', 'Oddiy'), ('low', 'Past')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesmessage',
            name='telegram_sent',
            field=models.BooleanField(default=False, help_text='Telegram orqali yuborilganligi'),
        ),
        migrations.CreateModel(
            name='SalesMessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='crm_app.salesmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message', 'user')},
            },
        ),
    ]
