# Generated by Django 4.2.7 on 2025-12-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_remove_salesmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['due_date', 'completed'], name='followup_due_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['sales', 'completed'], name='followup_sales_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['lead', 'completed'], name='followup_lead_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['is_overdue', 'completed'], name='followup_overdue_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['due_date'], name='followup_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['sales', 'date'], name='kpi_sales_date_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['date'], name='kpi_date_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'assigned_sales'], name='lead_status_sales_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='lead_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='lead_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='lead_source_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_sales', 'status'], name='lead_sales_status_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['sales', 'status'], name='leave_sales_status_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', 'start_date'], name='leave_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='triallesson',
            index=models.Index(fields=['date', 'time'], name='trial_date_time_idx'),
        ),
        migrations.AddIndex(
            model_name='triallesson',
            index=models.Index(fields=['lead', 'date'], name='trial_lead_date_idx'),
        ),
        migrations.AddIndex(
            model_name='triallesson',
            index=models.Index(fields=['result'], name='trial_result_idx'),
        ),
        migrations.AddIndex(
            model_name='triallesson',
            index=models.Index(fields=['date', 'result'], name='trial_date_result_idx'),
        ),
    ]
