# Generated by Django 4.2.7 on 2025-12-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_followup_followup_due_completed_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='followup_sequence',
            field=models.IntegerField(blank=True, help_text='Ketma-ketlik raqami (contacted status uchun)', null=True),
        ),
    ]
