# Generated by Django 4.2.7 on 2025-12-08 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_followup_followup_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text="Bonus, chegirma yoki qo'shimcha taklif tafsilotlari")),
                ('offer_type', models.CharField(choices=[('discount', 'Chegirma'), ('bonus', 'Bonus'), ('package', 'Paket'), ('other', 'Boshqa')], default='discount', max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Shoshilinch'), ('high', 'Yuqori'), ('normal', 'Oddiy'), ('low', 'Past')], default='normal', max_length=20)),
                ('channel', models.CharField(choices=[('all', 'Barcha'), ('followup', 'Follow-up'), ('reactivation', 'Reaktivatsiya'), ('trial', 'Sinov'), ('general', 'Umumiy')], default='all', max_length=20)),
                ('audience', models.CharField(choices=[('all', 'Barchaga'), ('new', 'Yangi lid'), ('lost', "Yo'qotilgan lid"), ('reactivation', 'Reaktivatsiya lid'), ('trial', 'Sinovga yozilgan')], default='all', max_length=20)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text="Muayyan kurs uchun bo'lsa tanlang", null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'valid_until'], name='offer_active_until_idx'), models.Index(fields=['priority'], name='offer_priority_idx'), models.Index(fields=['channel', 'audience'], name='offer_channel_audience_idx')],
            },
        ),
    ]
