# Generated by Django 4.2.7 on 2025-12-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='secondary_phone',
            field=models.CharField(blank=True, help_text="Qo'shimcha telefon (ota-ona yoki qo'shimcha raqam)", max_length=20, null=True),
        ),
    ]
