# Generated by Django 4.2.7 on 2025-12-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_lead_secondary_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_group_id',
            field=models.CharField(blank=True, help_text='Telegram guruh ID (statistika yuborish uchun)', max_length=100, null=True),
        ),
    ]
