# Generated by Django 5.0.1 on 2026-01-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0011_user_telegram_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_courses',
            field=models.ManyToManyField(blank=True, help_text="Qaysi kurs(lar) uchun lidlarga javob beradi (bo'sh bo'lsa barcha kurslar)", related_name='assigned_sales', to='crm_app.course'),
        ),
    ]
