# Generated by Django 4.2.7 on 2025-11-27 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.IntegerField(default=90)),
                ('frequency_per_week', models.IntegerField(default=3)),
                ('room_capacity', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('days', models.CharField(choices=[('odd', 'Odd days'), ('even', 'Even days'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday'), ('mon_wed_fri', 'Mon/Wed/Fri'), ('tue_thu', 'Tue/Thu')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.IntegerField()),
                ('current_students', models.IntegerField(default=0)),
                ('trial_students', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['course', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('occupancy_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy', to='scheduling.room')),
            ],
            options={
                'ordering': ['date', 'time_start'],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['name'], name='scheduling__name_0ae179_idx'),
        ),
        migrations.AddField(
            model_name='group',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='scheduling.course'),
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.room'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='roomoccupancy',
            index=models.Index(fields=['room', 'date'], name='scheduling__room_id_bd3674_idx'),
        ),
        migrations.AddIndex(
            model_name='roomoccupancy',
            index=models.Index(fields=['date', 'time_start'], name='scheduling__date_ec4847_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomoccupancy',
            unique_together={('room', 'date', 'time_start', 'time_end')},
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['course'], name='scheduling__course__46aeab_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['days'], name='scheduling__days_68b9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['start_time'], name='scheduling__start_t_b3e07e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('course', 'name', 'days', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='scheduling__name_4700f8_idx'),
        ),
    ]
