# Generated by Django 4.2.7 on 2025-11-22 06:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rule_type', models.CharField(choices=[('conversion_rate', 'Aylanish darajasi'), ('response_time', 'Javob berish vaqti'), ('leads_contacted', "Bog'langan lidlar"), ('leads_converted', 'Aylantirilgan lidlar'), ('revenue', 'Daromad')], max_length=50)),
                ('comparison', models.CharField(choices=[('gte', 'Katta yoki teng'), ('lte', 'Kichik yoki teng'), ('eq', 'Teng'), ('between', 'Oraliqda')], max_length=10)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, help_text='Bitta chegaraviy qiymat', max_digits=10, null=True)),
                ('threshold_min', models.DecimalField(blank=True, decimal_places=2, help_text="Minimal chegaraviy qiymat ('oraliqda' taqqoslash uchun)", max_digits=10, null=True)),
                ('threshold_max', models.DecimalField(blank=True, decimal_places=2, help_text="Maksimal chegaraviy qiymat ('oraliqda' taqqoslash uchun)", max_digits=10, null=True)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Qoida bajarilganda bonus miqdori', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Qoida bajarilmasa jarima miqdori', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('evaluation_period_days', models.IntegerField(default=30, help_text="Baholash uchun qaytib ko'riladigan kunlar soni", validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KPI Qoidasi',
                'verbose_name_plural': 'KPI Qoidalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerKPISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Oyning birinchi kuni')),
                ('total_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_leads', models.IntegerField(default=0)),
                ('converted_leads', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_summaries', to='leads.seller')),
            ],
            options={
                'verbose_name': 'Sotuvchi KPI Xulosa',
                'verbose_name_plural': 'Sotuvchi KPI Xulosalari',
                'ordering': ['-month', '-seller'],
                'indexes': [models.Index(fields=['seller', 'month'], name='kpi_sellerk_seller__e88005_idx')],
                'unique_together': {('seller', 'month')},
            },
        ),
        migrations.CreateModel(
            name='KPICalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rule_met', models.BooleanField(default=False)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='kpi.kpirule')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_calculations', to='leads.seller')),
            ],
            options={
                'verbose_name': 'KPI Hisobi',
                'verbose_name_plural': 'KPI Hisoblari',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['seller', 'calculated_at'], name='kpi_kpicalc_seller__4850bb_idx'), models.Index(fields=['rule', 'calculated_at'], name='kpi_kpicalc_rule_id_5e38cb_idx')],
                'unique_together': {('seller', 'rule', 'period_start', 'period_end')},
            },
        ),
    ]
