# Generated by Django 4.2.7 on 2025-11-22 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField(help_text='SMS xabar matni')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('scheduled', 'Rejalashtirilgan'), ('running', 'Ishlamoqda'), ('completed', 'Tugallangan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20)),
                ('target_lead_status', models.CharField(blank=True, choices=[('new', 'Yangi'), ('contacted', "Bog'langan"), ('qualified', 'Sifatli'), ('converted', 'Aylantirilgan'), ('lost', "Yo'qotilgan")], help_text='Ushbu holatdagi lidlarni nishonga oling', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_sellers', models.ManyToManyField(blank=True, related_name='sms_campaigns', to='leads.seller')),
            ],
            options={
                'verbose_name': 'SMS Kampaniyasi',
                'verbose_name_plural': 'SMS Kampaniyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSCampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='campaigns.smscampaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='leads.lead')),
            ],
            options={
                'verbose_name': 'SMS Kampaniya Jurnali',
                'verbose_name_plural': 'SMS Kampaniya Jurnallari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='campaigns_s_campaig_b9e9e8_idx')],
            },
        ),
    ]
