# Generated by Django 4.2.7 on 2025-11-27 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('channel', models.CharField(choices=[('instagram', 'Instagram Ads'), ('telegram', 'Telegram Bot'), ('whatsapp', 'WhatsApp'), ('landing', 'Landing Page'), ('google_sheets', 'Google Sheets'), ('call', 'Call Tracking')], max_length=50)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('leads_generated', models.IntegerField(default=0)),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctr', models.DecimalField(decimal_places=2, default=0, help_text='Click-through rate %', max_digits=5)),
                ('cpl', models.DecimalField(decimal_places=2, default=0, help_text='Cost per lead', max_digits=10)),
                ('cpa', models.DecimalField(decimal_places=2, default=0, help_text='Cost per acquisition', max_digits=10)),
                ('enrollments_from_channel', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'channel'], name='analytics_m_date_b6b87a_idx')],
                'unique_together': {('date', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='LeadMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('new_leads_total', models.IntegerField(default=0)),
                ('new_leads_instagram', models.IntegerField(default=0)),
                ('new_leads_telegram', models.IntegerField(default=0)),
                ('new_leads_whatsapp', models.IntegerField(default=0)),
                ('new_leads_landing', models.IntegerField(default=0)),
                ('new_leads_google_sheets', models.IntegerField(default=0)),
                ('new_leads_excel', models.IntegerField(default=0)),
                ('new_leads_csv', models.IntegerField(default=0)),
                ('new_leads_call', models.IntegerField(default=0)),
                ('leads_contacted', models.IntegerField(default=0)),
                ('leads_interested', models.IntegerField(default=0)),
                ('leads_trial_scheduled', models.IntegerField(default=0)),
                ('leads_trial_attended', models.IntegerField(default=0)),
                ('leads_sales_offer', models.IntegerField(default=0)),
                ('leads_enrolled', models.IntegerField(default=0)),
                ('leads_lost', models.IntegerField(default=0)),
                ('leads_assigned_total', models.IntegerField(default=0)),
                ('leads_unassigned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_l_date_4a930b_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_groups', models.IntegerField(default=0)),
                ('full_groups', models.IntegerField(default=0)),
                ('near_full_groups', models.IntegerField(default=0)),
                ('empty_groups', models.IntegerField(default=0)),
                ('total_rooms', models.IntegerField(default=0)),
                ('rooms_in_use', models.IntegerField(default=0)),
                ('avg_room_occupancy', models.IntegerField(default=0)),
                ('total_trial_students', models.IntegerField(default=0)),
                ('expected_enrollments', models.IntegerField(default=0)),
                ('new_groups_recommended', models.IntegerField(default=0)),
                ('groups_to_combine', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_g_date_84c599_idx')],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='SalesKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('new_contacts', models.IntegerField(default=0)),
                ('followups_completed', models.IntegerField(default=0)),
                ('followups_overdue', models.IntegerField(default=0)),
                ('trials_scheduled', models.IntegerField(default=0)),
                ('trials_attended', models.IntegerField(default=0)),
                ('trials_no_show', models.IntegerField(default=0)),
                ('sales_offers_made', models.IntegerField(default=0)),
                ('enrollments', models.IntegerField(default=0)),
                ('lost_leads', models.IntegerField(default=0)),
                ('avg_response_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['salesperson', 'date'], name='analytics_s_salespe_1d8846_idx'), models.Index(fields=['date'], name='analytics_s_date_d7919d_idx')],
                'unique_together': {('salesperson', 'date')},
            },
        ),
    ]
